name: terraform-plan
on:
  pull_request:
    paths: ["terraform/**", ".github/workflows/**"]

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    env:
      TF_VAR_alarm_email: ${{ secrets.ALARM_EMAIL }}
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - uses: hashicorp/setup-terraform@v3
      - run: terraform fmt -check -recursive
      - run: terraform init
      - run: terraform validate
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: terraform
          additional_args: --minimum-severity HIGH --concise-output

      - run: terraform plan -no-color -out plan.out
      - run: terraform show -json plan.out > plan.json
      - name: Policy as Code (Conftest)
        uses: docker://openpolicyagent/conftest:latest
        with:
          args: test --policy policy plan.json
